cmd:
	source ~/Terraform/TerraformCloud/venv/bin/activate
	export PYTHONPATH=~/Terraform/TerraformCloud/venv/bin/python3.10

python3:
	python3 -m venv ~/TerraformCloud/venv
	pip3 install -r requirements.txt

clean:
	rm -rf '__pycache__'